-- ==========================================
-- Migration: contenttypes 0001_initial
-- ==========================================
BEGIN;
--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
COMMIT;

-- ==========================================
-- Migration: contenttypes 0002_remove_content_type_name
-- ==========================================
BEGIN;
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name" CASCADE;
COMMIT;

-- ==========================================
-- Migration: auth 0001_initial
-- ==========================================
BEGIN;
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
-- (no-op)
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
COMMIT;

-- ==========================================
-- Migration: auth 0002_alter_permission_name_max_length
-- ==========================================
BEGIN;
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
COMMIT;

-- ==========================================
-- Migration: auth 0003_alter_user_email_max_length
-- ==========================================
BEGIN;
--
-- Alter field email on user
--
-- (no-op)
COMMIT;

-- ==========================================
-- Migration: auth 0004_alter_user_username_opts
-- ==========================================
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ==========================================
-- Migration: auth 0005_alter_user_last_login_null
-- ==========================================
BEGIN;
--
-- Alter field last_login on user
--
-- (no-op)
COMMIT;

-- ==========================================
-- Migration: auth 0006_require_contenttypes_0002
-- ==========================================

-- ==========================================
-- Migration: auth 0007_alter_validators_add_error_messages
-- ==========================================
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ==========================================
-- Migration: auth 0008_alter_user_username_max_length
-- ==========================================
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ==========================================
-- Migration: auth 0009_alter_user_last_name_max_length
-- ==========================================
BEGIN;
--
-- Alter field last_name on user
--
-- (no-op)
COMMIT;

-- ==========================================
-- Migration: auth 0010_alter_group_name_max_length
-- ==========================================
BEGIN;
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
COMMIT;

-- ==========================================
-- Migration: auth 0011_update_proxy_permissions
-- ==========================================
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- ==========================================
-- Migration: auth 0012_alter_user_first_name_max_length
-- ==========================================
BEGIN;
--
-- Alter field first_name on user
--
-- (no-op)
COMMIT;

-- ==========================================
-- Migration: accounts 0001_initial
-- ==========================================
BEGIN;
--
-- Create model User
--
CREATE TABLE "accounts_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "phone" varchar(20) NOT NULL, "role" varchar(20) NOT NULL, "avatar" varchar(100) NULL, "birth_date" date NULL, "passport_number" varchar(32) NOT NULL, "email_verified" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
CREATE TABLE "accounts_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "accounts_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE INDEX "accounts_user_username_6088629e_like" ON "accounts_user" ("username" varchar_pattern_ops);
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_group_id_59c0b32f_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_52b62117_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_group_id_bd11a704_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_groups_user_id_52b62117" ON "accounts_user_groups" ("user_id");
CREATE INDEX "accounts_user_groups_group_id_bd11a704" ON "accounts_user_groups" ("group_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_user_id_e4f0a161_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_permission_id_113bb443_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_user_permissions_user_id_e4f0a161" ON "accounts_user_user_permissions" ("user_id");
CREATE INDEX "accounts_user_user_permissions_permission_id_113bb443" ON "accounts_user_user_permissions" ("permission_id");
COMMIT;

-- ==========================================
-- Migration: admin 0001_initial
-- ==========================================
BEGIN;
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" bigint NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
COMMIT;

-- ==========================================
-- Migration: admin 0002_logentry_remove_auto_add
-- ==========================================
BEGIN;
--
-- Alter field action_time on logentry
--
-- (no-op)
COMMIT;

-- ==========================================
-- Migration: admin 0003_logentry_add_action_flag_choices
-- ==========================================
BEGIN;
--
-- Alter field action_flag on logentry
--
-- (no-op)
COMMIT;

-- ==========================================
-- Migration: routes 0001_initial
-- ==========================================
BEGIN;
--
-- Create model City
--
CREATE TABLE "routes_city" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "name_ru" varchar(100) NULL, "name_ky" varchar(100) NULL, "name_en" varchar(100) NULL, "slug" varchar(110) NOT NULL UNIQUE, "region" varchar(100) NOT NULL, "region_ru" varchar(100) NULL, "region_ky" varchar(100) NULL, "region_en" varchar(100) NULL, "country" varchar(80) NOT NULL, "country_ru" varchar(80) NULL, "country_ky" varchar(80) NULL, "country_en" varchar(80) NULL, "latitude" numeric(9, 6) NULL, "longitude" numeric(9, 6) NULL, "is_active" boolean NOT NULL);
--
-- Create model Station
--
CREATE TABLE "routes_station" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL, "name_ru" varchar(150) NULL, "name_ky" varchar(150) NULL, "name_en" varchar(150) NULL, "address" varchar(255) NOT NULL, "address_ru" varchar(255) NULL, "address_ky" varchar(255) NULL, "address_en" varchar(255) NULL, "phone" varchar(32) NOT NULL, "latitude" numeric(9, 6) NULL, "longitude" numeric(9, 6) NULL, "is_active" boolean NOT NULL, "city_id" bigint NOT NULL);
--
-- Create model Route
--
CREATE TABLE "routes_route" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "code" varchar(20) NOT NULL UNIQUE, "distance_km" integer NOT NULL CHECK ("distance_km" >= 0), "duration_minutes" integer NOT NULL CHECK ("duration_minutes" >= 0), "description" text NOT NULL, "description_ru" text NULL, "description_ky" text NULL, "description_en" text NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "destination_id" bigint NOT NULL, "origin_id" bigint NOT NULL);
--
-- Create model RouteStop
--
CREATE TABLE "routes_routestop" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "order" smallint NOT NULL CHECK ("order" >= 0), "offset_minutes" integer NOT NULL CHECK ("offset_minutes" >= 0), "stop_minutes" smallint NOT NULL CHECK ("stop_minutes" >= 0), "route_id" bigint NOT NULL, "station_id" bigint NOT NULL);
--
-- Create constraint route_origin_ne_destination on model route
--
ALTER TABLE "routes_route" ADD CONSTRAINT "route_origin_ne_destination" CHECK (NOT ("origin_id" = ("destination_id")));
CREATE INDEX "routes_city_slug_91a8dbb1_like" ON "routes_city" ("slug" varchar_pattern_ops);
ALTER TABLE "routes_station" ADD CONSTRAINT "routes_station_city_id_45f0637a_fk_routes_city_id" FOREIGN KEY ("city_id") REFERENCES "routes_city" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "routes_station_city_id_45f0637a" ON "routes_station" ("city_id");
ALTER TABLE "routes_route" ADD CONSTRAINT "routes_route_destination_id_797f8cf3_fk_routes_station_id" FOREIGN KEY ("destination_id") REFERENCES "routes_station" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "routes_route" ADD CONSTRAINT "routes_route_origin_id_47db82b4_fk_routes_station_id" FOREIGN KEY ("origin_id") REFERENCES "routes_station" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "routes_route_code_d17db1e3_like" ON "routes_route" ("code" varchar_pattern_ops);
CREATE INDEX "routes_route_destination_id_797f8cf3" ON "routes_route" ("destination_id");
CREATE INDEX "routes_route_origin_id_47db82b4" ON "routes_route" ("origin_id");
ALTER TABLE "routes_routestop" ADD CONSTRAINT "routes_routestop_route_id_station_id_c7d613d7_uniq" UNIQUE ("route_id", "station_id");
ALTER TABLE "routes_routestop" ADD CONSTRAINT "routes_routestop_route_id_order_ed0fa4ad_uniq" UNIQUE ("route_id", "order");
ALTER TABLE "routes_routestop" ADD CONSTRAINT "routes_routestop_route_id_86b62a13_fk_routes_route_id" FOREIGN KEY ("route_id") REFERENCES "routes_route" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "routes_routestop" ADD CONSTRAINT "routes_routestop_station_id_c34cd126_fk_routes_station_id" FOREIGN KEY ("station_id") REFERENCES "routes_station" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "routes_routestop_route_id_86b62a13" ON "routes_routestop" ("route_id");
CREATE INDEX "routes_routestop_station_id_c34cd126" ON "routes_routestop" ("station_id");
COMMIT;

-- ==========================================
-- Migration: schedule 0001_initial
-- ==========================================
BEGIN;
--
-- Create model BusType
--
CREATE TABLE "schedule_bustype" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL, "name_ru" varchar(80) NULL, "name_ky" varchar(80) NULL, "name_en" varchar(80) NULL, "description" text NOT NULL, "description_ru" text NULL, "description_ky" text NULL, "description_en" text NULL, "seats_default" smallint NOT NULL CHECK ("seats_default" >= 0), "has_wifi" boolean NOT NULL, "has_ac" boolean NOT NULL, "has_toilet" boolean NOT NULL);
--
-- Create model Bus
--
CREATE TABLE "schedule_bus" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "plate_number" varchar(20) NOT NULL UNIQUE, "model_name" varchar(80) NOT NULL, "seats" smallint NOT NULL CHECK ("seats" >= 0), "rows" smallint NOT NULL CHECK ("rows" >= 0), "seats_per_row" smallint NOT NULL CHECK ("seats_per_row" >= 0), "photo" varchar(100) NULL, "is_active" boolean NOT NULL, "bus_type_id" bigint NOT NULL);
--
-- Create model Driver
--
CREATE TABLE "schedule_driver" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "full_name" varchar(150) NOT NULL, "phone" varchar(32) NOT NULL, "license_number" varchar(40) NOT NULL, "experience_years" smallint NOT NULL CHECK ("experience_years" >= 0), "photo" varchar(100) NULL, "is_active" boolean NOT NULL, "user_id" bigint NULL UNIQUE);
--
-- Create model Trip
--
CREATE TABLE "schedule_trip" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "departure_at" timestamp with time zone NOT NULL, "arrival_at" timestamp with time zone NULL, "base_price" numeric(10, 2) NOT NULL, "status" varchar(20) NOT NULL, "note" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "bus_id" bigint NOT NULL, "driver_id" bigint NULL, "route_id" bigint NOT NULL);
ALTER TABLE "schedule_bus" ADD CONSTRAINT "schedule_bus_bus_type_id_90dcc8c8_fk_schedule_bustype_id" FOREIGN KEY ("bus_type_id") REFERENCES "schedule_bustype" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "schedule_bus_plate_number_2f54fec1_like" ON "schedule_bus" ("plate_number" varchar_pattern_ops);
CREATE INDEX "schedule_bus_bus_type_id_90dcc8c8" ON "schedule_bus" ("bus_type_id");
ALTER TABLE "schedule_driver" ADD CONSTRAINT "schedule_driver_user_id_dae90b65_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "schedule_trip" ADD CONSTRAINT "schedule_trip_bus_id_000a44ff_fk_schedule_bus_id" FOREIGN KEY ("bus_id") REFERENCES "schedule_bus" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "schedule_trip" ADD CONSTRAINT "schedule_trip_driver_id_7ce088da_fk_schedule_driver_id" FOREIGN KEY ("driver_id") REFERENCES "schedule_driver" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "schedule_trip" ADD CONSTRAINT "schedule_trip_route_id_2e2c4596_fk_routes_route_id" FOREIGN KEY ("route_id") REFERENCES "routes_route" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "schedule_trip_bus_id_000a44ff" ON "schedule_trip" ("bus_id");
CREATE INDEX "schedule_trip_driver_id_7ce088da" ON "schedule_trip" ("driver_id");
CREATE INDEX "schedule_trip_route_id_2e2c4596" ON "schedule_trip" ("route_id");
CREATE INDEX "schedule_tr_departu_98679a_idx" ON "schedule_trip" ("departure_at");
CREATE INDEX "schedule_tr_route_i_19a324_idx" ON "schedule_trip" ("route_id", "departure_at");
COMMIT;

-- ==========================================
-- Migration: booking 0001_initial
-- ==========================================
BEGIN;
--
-- Create model Booking
--
CREATE TABLE "booking_booking" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "code" varchar(24) NOT NULL UNIQUE, "contact_name" varchar(150) NOT NULL, "contact_phone" varchar(32) NOT NULL, "contact_email" varchar(254) NOT NULL, "total_price" numeric(10, 2) NOT NULL, "status" varchar(12) NOT NULL, "note" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "expires_at" timestamp with time zone NULL, "trip_id" bigint NOT NULL, "user_id" bigint NULL);
--
-- Create model Ticket
--
CREATE TABLE "booking_ticket" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "seat_number" smallint NOT NULL CHECK ("seat_number" >= 0), "passenger_name" varchar(150) NOT NULL, "passenger_document" varchar(64) NOT NULL, "passenger_phone" varchar(32) NOT NULL, "is_child" boolean NOT NULL, "price" numeric(10, 2) NOT NULL, "status" varchar(12) NOT NULL, "code" varchar(24) NOT NULL UNIQUE, "created_at" timestamp with time zone NOT NULL, "booking_id" bigint NOT NULL, "trip_id" bigint NOT NULL);
--
-- Create index booking_boo_status_9e1025_idx on field(s) status, expires_at of model booking
--
CREATE INDEX "booking_boo_status_9e1025_idx" ON "booking_booking" ("status", "expires_at");
--
-- Alter unique_together for ticket (1 constraint(s))
--
ALTER TABLE "booking_ticket" ADD CONSTRAINT "booking_ticket_trip_id_seat_number_b5feaf8a_uniq" UNIQUE ("trip_id", "seat_number");
ALTER TABLE "booking_booking" ADD CONSTRAINT "booking_booking_trip_id_bb76bd3d_fk_schedule_trip_id" FOREIGN KEY ("trip_id") REFERENCES "schedule_trip" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "booking_booking" ADD CONSTRAINT "booking_booking_user_id_e1eb6912_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "booking_booking_code_4b3bbca3_like" ON "booking_booking" ("code" varchar_pattern_ops);
CREATE INDEX "booking_booking_trip_id_bb76bd3d" ON "booking_booking" ("trip_id");
CREATE INDEX "booking_booking_user_id_e1eb6912" ON "booking_booking" ("user_id");
ALTER TABLE "booking_ticket" ADD CONSTRAINT "booking_ticket_booking_id_6e4cf6ea_fk_booking_booking_id" FOREIGN KEY ("booking_id") REFERENCES "booking_booking" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "booking_ticket" ADD CONSTRAINT "booking_ticket_trip_id_962f6fac_fk_schedule_trip_id" FOREIGN KEY ("trip_id") REFERENCES "schedule_trip" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "booking_ticket_code_43e6bf3d_like" ON "booking_ticket" ("code" varchar_pattern_ops);
CREATE INDEX "booking_ticket_booking_id_6e4cf6ea" ON "booking_ticket" ("booking_id");
CREATE INDEX "booking_ticket_trip_id_962f6fac" ON "booking_ticket" ("trip_id");
COMMIT;

-- ==========================================
-- Migration: core 0001_initial
-- ==========================================
BEGIN;
--
-- Create model ContactMessage
--
CREATE TABLE "core_contactmessage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL, "email" varchar(254) NOT NULL, "phone" varchar(32) NOT NULL, "subject" varchar(200) NOT NULL, "message" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "is_processed" boolean NOT NULL);
--
-- Create model FAQ
--
CREATE TABLE "core_faq" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "question" varchar(255) NOT NULL, "question_ru" varchar(255) NULL, "question_ky" varchar(255) NULL, "question_en" varchar(255) NULL, "answer" text NOT NULL, "answer_ru" text NULL, "answer_ky" text NULL, "answer_en" text NULL, "order" smallint NOT NULL CHECK ("order" >= 0), "is_active" boolean NOT NULL);
--
-- Create model HeroBanner
--
CREATE TABLE "core_herobanner" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "title_ru" varchar(200) NULL, "title_ky" varchar(200) NULL, "title_en" varchar(200) NULL, "subtitle" varchar(300) NOT NULL, "subtitle_ru" varchar(300) NULL, "subtitle_ky" varchar(300) NULL, "subtitle_en" varchar(300) NULL, "image" varchar(100) NULL, "cta_text" varchar(80) NOT NULL, "cta_text_ru" varchar(80) NULL, "cta_text_ky" varchar(80) NULL, "cta_text_en" varchar(80) NULL, "cta_url" varchar(255) NOT NULL, "order" smallint NOT NULL CHECK ("order" >= 0), "is_active" boolean NOT NULL);
--
-- Create model NewsArticle
--
CREATE TABLE "core_newsarticle" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "title_ru" varchar(200) NULL, "title_ky" varchar(200) NULL, "title_en" varchar(200) NULL, "slug" varchar(220) NOT NULL UNIQUE, "summary" varchar(300) NOT NULL, "summary_ru" varchar(300) NULL, "summary_ky" varchar(300) NULL, "summary_en" varchar(300) NULL, "body" text NOT NULL, "body_ru" text NULL, "body_ky" text NULL, "body_en" text NULL, "cover" varchar(100) NULL, "published_at" timestamp with time zone NOT NULL, "is_published" boolean NOT NULL);
CREATE INDEX "core_newsarticle_slug_89eec238_like" ON "core_newsarticle" ("slug" varchar_pattern_ops);
COMMIT;

-- ==========================================
-- Migration: payments 0001_initial
-- ==========================================
BEGIN;
--
-- Create model Payment
--
CREATE TABLE "payments_payment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "method" varchar(20) NOT NULL, "amount" numeric(10, 2) NOT NULL, "status" varchar(12) NOT NULL, "transaction_id" varchar(64) NOT NULL UNIQUE, "payer_name" varchar(150) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "raw_response" jsonb NULL, "booking_id" bigint NOT NULL);
ALTER TABLE "payments_payment" ADD CONSTRAINT "payments_payment_booking_id_2a46974b_fk_booking_booking_id" FOREIGN KEY ("booking_id") REFERENCES "booking_booking" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "payments_payment_transaction_id_55f6af3a_like" ON "payments_payment" ("transaction_id" varchar_pattern_ops);
CREATE INDEX "payments_payment_booking_id_2a46974b" ON "payments_payment" ("booking_id");
COMMIT;

-- ==========================================
-- Migration: sessions 0001_initial
-- ==========================================
BEGIN;
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;
