# Generated by Django 5.1.15 on 2026-05-23 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('question_ru', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_ky', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('question_en', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('answer_ru', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_ky', models.TextField(null=True, verbose_name='Ответ')),
                ('answer_en', models.TextField(null=True, verbose_name='Ответ')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('subtitle_ky', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Подзаголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Изображение')),
                ('cta_text', models.CharField(blank=True, max_length=80, verbose_name='Текст кнопки')),
                ('cta_text_ru', models.CharField(blank=True, max_length=80, null=True, verbose_name='Текст кнопки')),
                ('cta_text_ky', models.CharField(blank=True, max_length=80, null=True, verbose_name='Текст кнопки')),
                ('cta_text_en', models.CharField(blank=True, max_length=80, null=True, verbose_name='Текст кнопки')),
                ('cta_url', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Слаг')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('summary_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('summary_ky', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('summary_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('body', models.TextField(verbose_name='Текст')),
                ('body_ru', models.TextField(null=True, verbose_name='Текст')),
                ('body_ky', models.TextField(null=True, verbose_name='Текст')),
                ('body_en', models.TextField(null=True, verbose_name='Текст')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Обложка')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликована')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликована')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-published_at',),
            },
        ),
    ]
