# Generated by Django 5.1.15 on 2026-05-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Город')),
                ('name_ky', models.CharField(max_length=100, null=True, verbose_name='Город')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Город')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Слаг')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион/Область')),
                ('region_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион/Область')),
                ('region_ky', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион/Область')),
                ('region_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион/Область')),
                ('country', models.CharField(default='Кыргызстан', max_length=80, verbose_name='Страна')),
                ('country_ru', models.CharField(default='Кыргызстан', max_length=80, null=True, verbose_name='Страна')),
                ('country_ky', models.CharField(default='Кыргызстан', max_length=80, null=True, verbose_name='Страна')),
                ('country_en', models.CharField(default='Кыргызстан', max_length=80, null=True, verbose_name='Страна')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название автовокзала')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='Название автовокзала')),
                ('name_ky', models.CharField(max_length=150, null=True, verbose_name='Название автовокзала')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Название автовокзала')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('address_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('address_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='routes.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Автовокзал',
                'verbose_name_plural': 'Автовокзалы',
                'ordering': ('city__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код маршрута')),
                ('distance_km', models.PositiveIntegerField(default=0, verbose_name='Расстояние, км')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Длительность, мин')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_in', to='routes.station', verbose_name='Куда')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes_out', to='routes.station', verbose_name='Откуда')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'ordering': ('origin__city__name', 'destination__city__name'),
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('offset_minutes', models.PositiveIntegerField(default=0, verbose_name='Смещение от старта, мин')),
                ('stop_minutes', models.PositiveSmallIntegerField(default=5, verbose_name='Стоянка, мин')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='routes.station')),
            ],
            options={
                'verbose_name': 'Промежуточная остановка',
                'verbose_name_plural': 'Промежуточные остановки',
                'ordering': ('route', 'order'),
                'unique_together': {('route', 'order'), ('route', 'station')},
            },
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='route_origin_ne_destination'),
        ),
    ]
