# Generated by Django 5.1.15 on 2026-05-23 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('card', 'Банковская карта'), ('elcart', 'Элкарт'), ('mbank', 'MBank'), ('opay', 'O!Деньги'), ('cash', 'Наличные в кассе')], max_length=20, verbose_name='Метод')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('failed', 'Ошибка'), ('refunded', 'Возврат')], default='pending', max_length=12, verbose_name='Статус')),
                ('transaction_id', models.CharField(blank=True, max_length=64, unique=True, verbose_name='ID транзакции')),
                ('payer_name', models.CharField(blank=True, max_length=150, verbose_name='Плательщик')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Ответ')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking', verbose_name='Бронь')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
