# Generated by Django 5.1.15 on 2026-05-23 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Тип транспорта')),
                ('name_ru', models.CharField(max_length=80, null=True, verbose_name='Тип транспорта')),
                ('name_ky', models.CharField(max_length=80, null=True, verbose_name='Тип транспорта')),
                ('name_en', models.CharField(max_length=80, null=True, verbose_name='Тип транспорта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_ky', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('seats_default', models.PositiveSmallIntegerField(default=20, verbose_name='Кол-во мест по умолчанию')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('has_ac', models.BooleanField(default=True, verbose_name='Кондиционер')),
                ('has_toilet', models.BooleanField(default=False, verbose_name='Туалет')),
            ],
            options={
                'verbose_name': 'Тип транспорта',
                'verbose_name_plural': 'Типы транспорта',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('model_name', models.CharField(max_length=80, verbose_name='Модель')),
                ('seats', models.PositiveSmallIntegerField(default=20, verbose_name='Количество мест')),
                ('rows', models.PositiveSmallIntegerField(default=5, verbose_name='Рядов')),
                ('seats_per_row', models.PositiveSmallIntegerField(default=4, verbose_name='Мест в ряду')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='buses/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='schedule.bustype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Транспорт',
                'verbose_name_plural': 'Транспорт',
                'ordering': ('plate_number',),
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('license_number', models.CharField(blank=True, max_length=40, verbose_name='Удостоверение')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Стаж, лет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_at', models.DateTimeField(verbose_name='Отправление')),
                ('arrival_at', models.DateTimeField(blank=True, null=True, verbose_name='Прибытие')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена билета, сом')),
                ('status', models.CharField(choices=[('scheduled', 'По расписанию'), ('boarding', 'Идёт посадка'), ('departed', 'В пути'), ('arrived', 'Прибыл'), ('canceled', 'Отменён')], default='scheduled', max_length=20, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='schedule.bus', verbose_name='Транспорт')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='schedule.driver', verbose_name='Водитель')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейсы',
                'ordering': ('departure_at',),
                'indexes': [models.Index(fields=['departure_at'], name='schedule_tr_departu_98679a_idx'), models.Index(fields=['route', 'departure_at'], name='schedule_tr_route_i_19a324_idx')],
            },
        ),
    ]
