# Generated by Django 5.1.15 on 2026-05-23 20:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Код брони')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Имя контакта')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Итого')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачена'), ('canceled', 'Отменена'), ('refunded', 'Возврат'), ('expired', 'Истекла')], default='pending', max_length=12, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='schedule.trip', verbose_name='Рейс')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveSmallIntegerField(verbose_name='Место')),
                ('passenger_name', models.CharField(max_length=150, verbose_name='ФИО пассажира')),
                ('passenger_document', models.CharField(blank=True, max_length=64, verbose_name='Документ')),
                ('passenger_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('is_child', models.BooleanField(default=False, verbose_name='Ребёнок')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('status', models.CharField(choices=[('booked', 'Забронирован'), ('paid', 'Оплачен'), ('canceled', 'Отменён'), ('used', 'Использован')], default='booked', max_length=12, verbose_name='Статус')),
                ('code', models.CharField(blank=True, max_length=24, unique=True, verbose_name='Код билета')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.booking')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='schedule.trip')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
                'ordering': ('trip__departure_at', 'seat_number'),
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'expires_at'], name='booking_boo_status_9e1025_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('trip', 'seat_number')},
        ),
    ]
